name = "cloud-mail-dev"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[dev]
ip = "0.0.0.0"

[[d1_databases]]
binding = "db"
database_name = "db"
database_id = "2e27e91f-7e56-4b85-aac1-c32145bfc879"

[[kv_namespaces]]
binding = "kv"
id = "d50d12866e0841918e5183d295494f48"

#[[r2_buckets]]
#binding = "r2"
#bucket_name = "email"

#[ai]
#binding = "ai"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

#[[send_email]]
#name = "email"


[vars]
ai_model = ""
analysis_cache = false
orm_log = false
domain = ["walendowski.pl"]
admin = "admin@walendowski.pl"
jwt_secret = "0fa495d1defd9d1806e1b4dac17da64d1646da9fcc6fa2d423ce541e92d9c167"
